{
 "title": "Monitoramento Sistema",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Consumo de Memória (RAM)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tms_cadastro,$__interval),\n  avg(memoria) AS \"memoria\"\nFROM tb_monitoramento\nGROUP BY 1\nORDER BY $__timeGroup(tms_cadastro,$__interval)"
    }
   ]
  },
  {
   "title": "Acessos - Login",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tms_cadastro,$__interval),\n  avg(acessos) AS \"acessos\"\nFROM tb_monitoramento\nWHERE\n  $__timeFilter(tms_cadastro)\nGROUP BY 1\nORDER BY $__timeGroup(tms_cadastro,$__interval)"
    }
   ]
  },
  {
   "title": "Consumo de Armazenamento (HD/SSD)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  tms_cadastro AS \"time\",\n   (100 - armazenamento) AS Livre,\n  armazenamento AS \"Ocupado\"\nFROM tb_monitoramento\nWHERE\n  $__timeFilter(tms_cadastro)\nORDER BY tms_cadastro"
    }
   ]
  },
  {
   "title": "Armazenamento - Histórico",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tms_cadastro,$__interval),\n  avg(armazenamento) AS \"armazenamento\"\nFROM tb_monitoramento\nWHERE\n  $__timeFilter(tms_cadastro)\nGROUP BY 1\nORDER BY $__timeGroup(tms_cadastro,$__interval)"
    }
   ]
  }
 ]
}